project: helmet-reflect

train: /home/work/datasets/yolo/images/train/
val: /home/work/datasets/yolo/images/val/

# number of classes
nc: 3

# class names
names: ['hat', 'person', 'reflective_clothes']
